The K2 Migration (feat. The Compose Compiler Gradle Plugin)
droidconKE/droidconKeKotlin pull request #286
Opened 2024-05-24 23:46 UTC by emmanuelmuturia

# Scope
- Migrated to Kotlin version 2.0.0 and upgraded relevant libraries (versions)...
- Added the Compose Compiler Gradle Plugin to the :app, :chai, and :presentation modules...
- Removed the references to the older Compose Compiler...

_Please make sure to read the [Contribution Guidelines](https://github.com/droidconKE/droidconKE2023Android/blob/main/CONTRIBUTING.md)
and check that you understand and have followed it as best as possible Explain what your feature
does in a short paragraph._ please check the below boxes
- [✔] I have followed the coding conventions
- [] I have added/updated necessary tests
- [] I have tested the changes added on a physical device
- [✔] I have run `./codeAnalysis.sh` on linux/unix or `codeAnalysys.bat` on windows to make sure all lint/formatting checks have been done.

## Closes/Fixes Issues
_Declare any issues by typing `fixes #1` or `closes #1` for example so that the automation can kick
in when this is merged_

## Other testing QA Notes
_What have you tested specifically and what possible impacts/areas there are that may need retesting
by others._

Please add a screenshot (if necessary)

2024-06-05 10:25 UTC, chepsi commented
@emmanuelmuturia  I have fixed the failing CI with my latest merge please rebase from develop

2024-06-05 14:11 UTC, emmanuelmuturia commented
I have rebased my work as requested...

2024-06-05 17:06 UTC, kibettheophilus commented
@emmanuelmuturia I see there are alot of of committed build generated files(the new modules under `shared`), can you please delete then add them to `.gitignore`?

2024-06-05 18:14 UTC, emmanuelmuturia commented
@kibettheophilus I have rewritten my commit history and added the build-generated files to `.gitignore` as advised...

2024-06-05 19:25 UTC, kibettheophilus commented
> @kibettheophilus I have rewritten my commit history and added the build-generated files to `.gitignore` as advised...



> @kibettheophilus I have rewritten my commit history and added the build-generated files to `.gitignore` as advised...



> @kibettheophilus I have rewritten my commit history and added the build-generated files to `.gitignore` as advised...

I see there are still generated files, can you delete all the changes you have `shared/.....`

2024-06-06 05:33 UTC, emmanuelmuturia commented
@kibettheophilus Please check if my latest push matches your recommendation...

2024-06-06 06:10 UTC, kibettheophilus approved these changes
LGTM

2024-06-06 06:12 UTC, chepsi commented on app/build.gradle.kts
> +    alias(notation = libs.plugins.compose.compiler)
why is this named?

2024-06-06 06:12 UTC, chepsi commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">DroidConKE</string>
🏅

2024-06-06 06:14 UTC, chepsi commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">DroidConKE</string>
`DroidConKE` -> `DroiconKe`

2024-06-06 06:15 UTC, chepsi commented on chai/build.gradle.kts
> +    alias(notation = libs.plugins.compose.compiler)
Minor: Why is this named?

2024-06-06 06:15 UTC, chepsi approved these changes
LGTM

2024-06-06 06:43 UTC, kibettheophilus requested changes
Hey @emmanuelmuturia your latest push added the build files, please check again

2024-06-06 06:44 UTC, emmanuelmuturia commented
@chepsi I have implemented the minor corrections as suggested...

2024-06-06 07:22 UTC, emmanuelmuturia commented
@kibettheophilus @chepsi Please confirm if everything is all good now...

2024-06-06 07:25 UTC, kibettheophilus approved these changes

2024-06-06 07:25 UTC, kibettheophilus commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">Droidconke</string>
```suggestion
    <string name="app_name">DroidconKe</string>
```

2024-06-06 07:26 UTC, kibettheophilus commented
> @kibettheophilus @chepsi Please confirm if everything is all good now...

looks good now

2024-06-06 07:44 UTC, merged

2024-06-06 23:26 UTC, etonotieno commented
K2 adds [a new `.kotlin` directory](https://kotlinlang.org/docs/whatsnew20.html#new-directory-for-kotlin-data-in-gradle-projects) for Gradle projects which should be ignored by git.

@kibettheophilus @chepsi

2024-06-07 05:37 UTC, kibettheophilus commented
> K2 adds [a new `.kotlin` directory](https://kotlinlang.org/docs/whatsnew20.html#new-directory-for-kotlin-data-in-gradle-projects) for Gradle projects which should be ignored by git.
> 
> ![image](https://private-user-images.githubusercontent.com/25648109/337467255-3deb16a4-4ce3-41c0-b314-0a1a6296a5ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3Mzg4NjcsIm5iZiI6MTcxNzczODU2NywicGF0aCI6Ii8yNTY0ODEwOS8zMzc0NjcyNTUtM2RlYjE2YTQtNGNlMy00MWMwLWIzMTQtMGExYTYyOTZhNWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA1MzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NGM4ZTEzMTg5ZGJkZGRjNzBlYzc5OGVmNjFmMmE0ZWY3OTgyNTg4MjFlMzVjODBjZGNhMmFmZjQ1OTgyMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hdtNo54ofUtetqDtIeZb84Soc4UQxYd-ho3l7FvxwAw)
> 
> @kibettheophilus @chepsi

@etonotieno correct, let me add it

2024-06-07 05:40 UTC, kibettheophilus commented
@etonotieno review https://github.com/droidconKE/droidconKeKotlin/pull/300